global:
  scrape_interval: 5s # Fréquence de scraping ultra-courte pour le temps réel
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'nexus-core-cluster'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          environment: 'production'
          tier: 'high-frequency-trading'
